import { cards, type Card } from "@/utils/mocks/cards.mocks"

export type CardGroupHeader = {
  id: string
  title: string
  circleColor: string
}

export type CardGroup = CardGroupHeader & {
  cards: Card[]
}

/**
 * The color is generated by generateStatusColor().
 * The idea behind that is that once we have an actual DB, the value will be stored there
 * using the same function.
 */

export const groupedCards: CardGroup[] = [
  {
    id: "e-55dZDINc",
    title: "Todo",
    circleColor: "hsl(53,91%,56%)",
    cards: [...cards.filter((card) => card.status === "todo")],
  },
  {
    id: "mVgWw6y5e6",
    title: "Doing",
    circleColor: "hsl(37,72%,50%)", // generateStatusColor(),
    cards: [...cards.filter((card) => card.status === "doing")],
  },
  {
    id: "Qnit6ESA4q",
    title: "Done",
    circleColor: "hsl(138,55%,41%)", // generateStatusColor(),
    cards: [...cards.filter((card) => card.status === "done")],
  },
]
