### Health check
GET http://localhost:4000/v1/healthcheck
###

### Get all of the boards
GET http://localhost:4000/v1/boards
Content-Type: application/json
###

### Get specific board by an ID
GET http://localhost:4000/v1/boards/3fca43e5-7aac-4ae8-97f8-f028246dbe92
Content-Type: application/json
###

### Create a new board
POST http://localhost:4000/v1/boards
Content-Type: application/json

{"name": "Platform Launch", "columns":  [{ "name": "Todo" }, { "name": "Doing" }]}
###


### Update a board
PUT http://localhost:4000/v1/boards/3fca43e5-7aac-4ae8-97f8-f028246dbe92
Content-Type: application/json

{"id":  "3fca43e5-7aac-4ae8-97f8-f028246dbe92", "name": "Updated Platform launch", "columns":  [{ "id": "6e092df7-42c7-4fff-8988-9033fc661a57", "name": "(Updated) Todo" }, { "name": "In progress" }, { "name": "Done" }]}
###

### Delete specific board by an ID
DELETE http://localhost:4000/v1/boards/a231b3fd-72e7-4f2b-a79d-6f3b226bf43f
Content-Type: application/json
###

### Get all columns by an ID
GET http://localhost:4000/v1/boards/55494f14-8bb8-4db9-940d-223b4a4e4067/columns
Content-Type: application/json
###